### ISSUE TITLE
Run Without composer

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [AYLIEN/aylien_textapi_php#2]
i am creating simple project without composer..

how can i run this API without composer ??

**Comment by amir** [comment]
You should be able to clone this repository and `require` it like any other library. e.g.,
```
require_once("aylien_textapi_php/src/AYLIEN/TextAPI.php");
```

**Comment by nilaybrahmbhatt** [comment]
please view this errors.....
(https://cloud.githubusercontent.com/assets/6310631/17132809/f917db10-5340-11e6-8c08-424d36305886.png)

**Comment by amir** [comment]
Can you disable https? When creating an instance of `AYLIEN\TextAPI` pass a third parameter with value false. e.g.,

```php
$textapi = new AYLIEN\TextAPI("YourApplicationId", "YourApplicationKey", false);
```

instead of

```php
$textapi = new AYLIEN\TextAPI("YourApplicationId", "YourApplicationKey");
```

**Comment by rajakhurramjaved** [comment]
Hi Amir, 
I am using it like this
<?php
	include_once("AYLIEN/TextAPI.php");
	$textapi = new AYLIEN\TextAPI("xyz", "pqr");
	$text = "John is good football player"
	$entities = $textapi->Entities(array('text' => $text));
	foreach ($entities->entities as $type => $values) {
	  printf($type . ": " . implode(', ', $values) . "\n");
	}
?>
and getting error.

Warning: Invalid argument supplied for foreach() in E:\wamp\www\university\analysis.php on line 5 
i.e. foreach....
can you please guide me where i am wrong?
