### ISSUE TITLE
Missing raw html option in TextAPI.php

### ISSUE THREAD

**Issue by kylescousin** [AYLIEN/aylien_textapi_php#4]
In the docs here: https://docs.aylien.com/textapi/endpoints/#article-extraction

It says you can either provide a url or raw html.

The raw html option is not working because it throws an exception if no url is provided.

```
if (empty($params['url'])) {
      throw new \BadMethodCallException("You must provide a url");
    }
```

**Comment by mdibaiee** [comment]
@kylescousin Thanks for reporting the issue in. This has been fixed in `v0.8.0`, please test and report back to us if the issue persists.
